FROM microsoft/dotnet:2.2-sdk

WORKDIR /test

COPY MicroServiceTests/MicroService.Tests.csproj ./MicroService.Tests/
COPY MicroService/MicroService.csproj ./MicroService/
RUN dotnet restore MicroService.Tests/MicroService.Tests.csproj

COPY MicroService MicroService
COPY MicroService.Tests MicroService.Tests
RUN dotnet test MicroService.Tests/MicroService.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info /p:Include="[MicroService]*"
