FROM microsoft/dotnet:2.2-sdk

WORKDIR /test

COPY MicroServiceTests/MicroServiceTests.csproj ./MicroServiceTests/
COPY MicroService/MicroService.csproj ./MicroService/
RUN dotnet restore MicroServiceTests/MicroServiceTests.csproj

COPY MicroService MicroService
COPY MicroServiceTests MicroServiceTests
RUN dotnet test MicroServiceTests/MicroServiceTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info /p:Include="[MicroService]*"
